name: Generate ASCII

on: push

jobs:
    ascii_job:
      runs_on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

        - name: Install cowsay
          run: sudo apt install cowsay -y

        - name: Execuse Cowsay
          run: cowsay "Mooo" >> cow.txt

        - name: Test File Exists
          run: grep -i "mooo" cow.txt

        - name: Read File
          run: cat cow.txt

        - name: List files
          run: ls -ltra


